services:
  backend_server:
    container_name: backend_server
    depends_on:
      - backend_redis
    restart: on-failure
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      REDIS_HOST: backend_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  backend_redis:
    container_name: backend_redis
    image: redis
    ports:
      - "0.0.0.0:6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_config:/usr/local/etc/redis

volumes:
  redis_config: