FROM amazoncorretto:17-alpine
WORKDIR /back
COPY . .
RUN chmod +x gradlew && ./gradlew clean build --no-build-cache
ENTRYPOINT ["java", "-Duser.timezone=Asia/Seoul", "-jar", "build/libs/qookie-0.0.1-SNAPSHOT.jar"]
