FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
#CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout=300", "--log-level=info", "app:app"]
CMD []