server:
  port: 8000
  ssl:
    enabled: false
spring:
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
rabbitmq:
  host: localhost
  port: 5672
  user: newjeans
  password: ss501ss501